### PR TITLE
Made a minor change

### PR DESCRIPTION
**Pull request by abdulbasetbappy**
nbfdhgf d hgfdhgfd hgfdgf dfd hgf

### CODE REVIEW

**Comment by abdulbasetbappy** [comment]
dfhgfdhg

**Comment by firstquarterlee** [comment]
Why Closeing?

**Comment by ahumiri** [comment]
nice

**Comment by Litalhag** [comment]
Thank you for the video! I didn't finish it, I just started to learn :)
Nice to meet you, I'm Lital from Israel

**Pull request closed without merging**
