### PR TITLE
Create Testing badges for pull request

### PR DESCRIPTION
**Pull request by codeTun**

### CODE REVIEW

**Comment by codeTun** [comment]
Test

**Comment by kanhaiya8608** [comment]
❤️

**Comment by mwarcc** [comment]
❤️

**Comment by Rayyan7878** [comment]
'❤

**Comment by WaddlesADuck** [comment]
test

**Comment by obunga99** [comment]
test

**Comment by Dante-Navaza2005** [comment]
❤️

**Comment by Rayyan7878** [comment]
❤❤

**Comment by Enesphlvn** [comment]
❤

**Comment by codeTun** [comment]
<3

**Comment by rsalim0** [comment]
❤

**Pull request closed without merging**
